version: "3"
services:
  steemfounders:
    build: .
    ports: 
      - "8080:8080"
    environment:
      - DOMAIN=example.com
      - WEBSITE_URL=https://example.com
      # - DATABASE_URL=#
      - MAILGUN_DOMAIN=#
      - MAILGUN_API_KEY=#
      - STEEM_USERNAME=#
      - POSTING_KEY=#
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

volumes:
  db-data: